# Generated by Django 5.2.5 on 2025-10-02 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultydata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='weight',
            field=models.IntegerField(default=1),
        ),
    ]
