# Generated by Django 5.2.5 on 2025-10-08 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultydata', '0002_alter_subject_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='class_obj',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='is_lab',
        ),
        migrations.AddField(
            model_name='subject',
            name='tutorial',
            field=models.BooleanField(default=False, help_text='Check if subject has tutorial hours'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subject',
            name='weight',
            field=models.PositiveIntegerField(default=0, help_text='Number of periods per week'),
        ),
    ]
