# Generated by Django 5.2.5 on 2025-10-08 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('facultydata', '0003_remove_subject_class_obj_remove_subject_is_lab_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='tutorial',
        ),
        migrations.AddField(
            model_name='subject',
            name='class_obj',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='classes.classroom'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='is_lab',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='subject',
            name='weight',
            field=models.IntegerField(default=1),
        ),
    ]
