# Generated by Django 5.2.5 on 2025-10-08 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultydata', '0004_remove_subject_tutorial_subject_class_obj_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='is_lab',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='weight',
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
