# Generated by Django 5.2.5 on 2025-10-08 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultydata', '0005_remove_subject_is_lab_remove_subject_weight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='class_obj',
        ),
        migrations.AddField(
            model_name='subject',
            name='tutorial',
            field=models.BooleanField(default=False, help_text='Check if subject has tutorial hours'),
        ),
        migrations.AddField(
            model_name='subject',
            name='weight',
            field=models.PositiveIntegerField(default=0, help_text='Number of periods per week'),
        ),
    ]
