# Generated by Django 5.2.5 on 2025-10-08 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('facultydata', '0006_remove_subject_class_obj_subject_tutorial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='class_obj',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='classes.classroom'),
            preserve_default=False,
        ),
    ]
