# Generated by Django 5.2.5 on 2025-10-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('facultydata', '0007_subject_class_obj'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='classes',
            field=models.ManyToManyField(to='classes.classroom'),
        ),
    ]
