# Generated by Django 5.2.5 on 2025-10-08 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('facultydata', '0008_faculty_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='is_lab',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subject',
            name='is_mini',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subject',
            name='class_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.classroom'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='tutorial',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subject',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
