# Generated by Django 5.2.5 on 2025-10-08 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultydata', '0009_subject_is_lab_subject_is_mini_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facultydata.faculty'),
        ),
    ]
