# Generated by Django 5.2.5 on 2025-10-08 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('facultydata', '0010_alter_subject_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='classes',
            field=models.ManyToManyField(blank=True, to='classes.classroom'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='class_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='classes.classroom'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='facultydata.faculty'),
        ),
    ]
